In [1]:
import tensorflow as tf
import numpy as np
import math
import timeit
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
def unpickle(file):
    import pickle
    with open(file,'rb') as fo:
        dict = pickle.load(fo,encoding='bytes')
    return dict

In [3]:
batch_1 = unpickle('data_batch_1')
test_batch = unpickle('test_batch')

In [4]:
batch_1.keys()

dict_keys([b'batch_label', b'labels', b'data', b'filenames'])

In [10]:
X_train = batch_1[b'data']
Y_train = batch_1[b'labels']
X_test = test_batch[b'data']
Y_test = test_batch[b'labels']
Y_train = tf.one_hot(Y_train,10)
Y_test = tf.one_hot(Y_test,10)
X_train = tf.cast(X_train,tf.float32)
X_test = tf.cast(X_test,tf.float32)
sess = tf.Session()
X_train = X_train.eval(session=sess)
X_test = X_test.eval(session=sess)
Y_train = Y_train.eval(session=sess)
Y_test = Y_test.eval(session=sess)

In [11]:
X = tf.placeholder(tf.float32,[None,32,32,3])
y = tf.placeholder(tf.int64,[None])
is_training = tf.placeholder(tf.bool)



In [13]:
x = np.array(((2,1,3),(1,2,3),(4,5,6)))

In [15]:
print(x)

[[2 1 3]
 [1 2 3]
 [4 5 6]]
